server:
  port: 8888
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    discovery:
      enabled: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:9000"
              - "http://localhost:8761"
              - "http://localhost:8887"
              - "http://localhost:8886"
              - "http://localhost:8885"
              - "http://localhost:3000"
            allowedHeaders:
              - Content-Type
              - Authorization
            exposedHeaders:
              - Content-Type
              - Authorization
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowCredentials: true

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka